config/routes.rb
Rails.application.routes.draw do

  get 'pages_home'=> 'pages#home'
  get 'pages_landing'=> 'pages#landing'

   authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  root :to => "pages#landing"

resources :sports, only: :index

resources :countries, only: :index do
  resources :games, only: :index
end

# resources :users

resources :games, only: [:show, :top] do

  member do
    post :home
    post :away
  end

  resources :requests, only: [:index, :new, :create, :destroy]
end

  resources :requests, only: :index do

    member do
      post :display
    end

    resources :matches, only: [:new, :create]
  end

  resources :matches, only: [:index, :destroy]


  devise_for :users
  resources :users do
    resources :rbfriends, only: [:new, :destroy]
  end


  resources :rbfriends, only: :index do
    resources :betfriends, only: [:new, :destroy]
  end

  resources :betfriends, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


   # devise_for :users, controllers: {
   #      sessions: 'users/sessions'
   #    }

# devise_for :users,
#     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' },
#     path: "sessions"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/betfriend.rb
class Betfriend < ApplicationRecord
  belongs_to :rbfriend
  belongs_to :friend_a, class_name: 'User'
  belongs_to :friend_b, class_name: 'User'
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :sport
  has_many :games
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :request
end

app/models/rbfriend.rb
class Rbfriend < ApplicationRecord
  belongs_to :user
   belongs_to :send, class_name: 'User'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/requestf.rb
class Requestf < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    pages_home_path(resource)
   end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    pages_home_path(resource)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   redirect_to pages_home_path
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @matches = Match.where(user: @user)
    @matcher_r = Match.all
    @matches_win = Match.where(status: "Won")
    @matches_tie = Match.where(status: "Tie")
    @matches_lost = Match.where(status: "Lost")
    @requests = Rbfriend.where(user: current_user)

    @betfriends = Betfriend.all
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/betfriends_helper.rb
module BetfriendsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rbfriends_helper.rb
module RbfriendsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class = "container_games">
<div class = "countainer ">
  <div class ="row">
    <div class = "col-xs-10 col-sm-offset-4 col-md-8 col-md-offset-3 text-center">

  <div class ="details-user">

    <div class ="info">

    <ul class ="list-inline list-unstyled">
      <li> <h3><%=@user.email%></h3></li>
    <li><img src="https://image.flaticon.com/icons/svg/181/181549.svg" width="70" height="70"></li>
    </ul>
    </div>


    <div class ="country">
    <ul class ="list-inline list-unstyled">
      <li> <h4>Mexico</h4></li>
    <li><img src="https://image.flaticon.com/icons/svg/330/330433.svg " width="30" height="30"></li>
    </ul>

    </div>

    <div class ="coins">
     <ul class ="list-inline list-unstyled">
      <li> <h3>175</h3></li>
    <li><img src="https://image.flaticon.com/icons/svg/138/138292.svg" width="40" height="40"></li>
    </ul>


    </div>

  </div>

  <%count_wins = 0%>
  <%count_tie = 0%>
  <%count_lost = 0%>

  <%@matches_tie.each do |ties|%>
    <%if ties.user == @user || ties.request.user == @user%>
      <%=count_tie +=1%>
    <%end%>
  <%end%>

        <div class ="user-results">
          <div>
            <h2 class ="result-name">Wins</h2>
            <h4>1</h4>
          </div>

          <div>
            <h2 class ="result-name">Ties</h2>
            <h4><%=count_tie%></h4>
          </div>

          <div>
            <h2 class ="result-name">Lost</h2>
            <h4>3</h4>
          </div>
        </div>

        <%count = 0%>

      <%@matcher_r.each do |match_r|%>
        <%if match_r.user == @user || match_r.request.user == @user%>
          <%count += 1%>
        <%end%>
      <%end%>

      <p> You have <%=count%> mathces!!</p>


      <br>


        <%@requests.each do |request|%>
        <ul class = "list-unstyled list-inline">
           <%if @user == current_user%>
             <li> <p> You have a request from <%=link_to user_path(request.send.id) do %>
               <%=request.send.email%></p><%end%></li>
               <li><%=link_to "Confirm", new_rbfriend_betfriend_path(request.id), class: "btn btn-success"%></li>
               <li><%=link_to "Decline", user_rbfriend_path(request.user, request), :method => :delete, class: "btn btn-danger"%></li>
               </ul>

           <%end%>
        <%end%>

        <%if @user != current_user%>
          <%=link_to "+ Add as Betfrined", new_user_rbfriend_path(@user)%>
          <%else%>
          <h4 id ="show-friends"> See my Betfriends    <img src="https://www.flaticon.com/premium-icon/icons/svg/47/47352.svg" width="25" height="25"></h4>
          <%end%>
      <br>




      <%@betfriends.each do |betfriend|%>
         <%if betfriend.friend_b == current_user && @user == current_user%>

        <%=link_to user_path(betfriend.friend_a) do%>
          <div class ="friend initiallyHidden"> <%=betfriend.friend_a.email%></div>
        <%end%>

        <%elsif betfriend.friend_a== current_user && @user == current_user%>
        <%=link_to user_path(betfriend.friend_b) do%>
          <div class = "friend initiallyHidden"><%=betfriend.friend_b.email%></div>
          <%end%>
        <%end%>
      <%end%>

    </div>
  </div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>