config/routes.rb
Rails.application.routes.draw do

  get 'pages_home'=> 'pages#home'
  get 'pages_landing'=> 'pages#landing'

   authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  root :to => "pages#landing"

resources :sports, only: :index

resources :countries, only: :index do
  resources :games, only: :index
end

# resources :users

resources :games, only: [:show, :top] do

  member do
    post :home
    post :away
  end

  resources :requests, only: [:index, :new, :create, :destroy]
end

  resources :requests, only: :index do

    member do
      post :display
    end

    resources :matches, only: [:new, :create]
  end

  resources :matches, only: [:index, :destroy]


  devise_for :users
  resources :users do
    resources :rbfriends, only: [:new, :destroy]
  end


  resources :rbfriends, only: :index do
    resources :betfriends, only: [:new, :destroy]
  end

  resources :betfriends, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


   # devise_for :users, controllers: {
   #      sessions: 'users/sessions'
   #    }

# devise_for :users,
#     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' },
#     path: "sessions"
end

app/models/betfriend.rb
class Betfriend < ApplicationRecord
  belongs_to :rbfriend
  belongs_to :friend_a, class_name: 'User'
  belongs_to :friend_b, class_name: 'User'
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :sport
  has_many :games
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :request
end

app/models/rbfriend.rb
class Rbfriend < ApplicationRecord
  belongs_to :user
   belongs_to :send, class_name: 'User'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/requestf.rb
class Requestf < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/betfriends_helper.rb
module BetfriendsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rbfriends_helper.rb
module RbfriendsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/destroy.html.erb
<h1>Index#destroy</h1>
<p>Find me in app/views/index/destroy.html.erb</p>

app/views/index/new.html.erb
<h1>Index#new</h1>
<p>Find me in app/views/index/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class = "container ">
  <div class = "row">
    <div class = "col-md-6">
    <div class="pull-left">
      <ul class = "list-unstyled sidebar">
        <h3 class = "border">
        <%= link_to pages_home_path do %>
          <img src="https://attachment.outlook.office.net/owa/albertoaldanar@hotmail.com/service.svc/s/GetFileAttachment?id=AQMkADAwATY0MDABLWQwMAAyLWM4ZGQALTAwAi0wMAoARgAAA1f8KLAR%2BBlIo7LSGZ%2Bw8yAHACQviVWa2y5PuCWt%2BCU8H7EAAAIBDAAAAN92unImHcZNuOR8sjcx8ukAAABgiKkAAAEBEgAQADvj2ORtyahIvcDRvQuk3hs%3D&X-OWA-CANARY=bc6QUuBguUaJDtukPzXt7YBhYqfu0NQYJMHO3OpVYXHTN9XrD5_yRshRfTwNTjHVB04F54rH_jA.&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImVuaDlCSnJWUFU1aWpWMXFqWmpWLWZMMmJjbyJ9.eyJ2ZXIiOiJFeGNoYW5nZS5DYWxsYmFjay5WMSIsImFwcGN0eHNlbmRlciI6Ik93YURvd25sb2FkQDg0ZGY5ZTdmLWU5ZjYtNDBhZi1iNDM1LWFhYWFhYWFhYWFhYSIsImFwcGN0eCI6IntcIm1zZXhjaHByb3RcIjpcIm93YVwiLFwicHJpbWFyeXNpZFwiOlwiUy0xLTI4MjctNDA5NjAwLTM0ODk4NDM0MjFcIixcInB1aWRcIjpcIjE3NTkyMjIwOTQyODUwMjFcIixcIm9pZFwiOlwiMDAwNjQwMDAtZDAwMi1jOGRkLTAwMDAtMDAwMDAwMDAwMDAwXCIsXCJzY29wZVwiOlwiT3dhRG93bmxvYWRcIn0iLCJpc3MiOiIwMDAwMDAwMi0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDBAODRkZjllN2YtZTlmNi00MGFmLWI0MzUtYWFhYWFhYWFhYWFhIiwiYXVkIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwL2F0dGFjaG1lbnQub3V0bG9vay5vZmZpY2UubmV0QDg0ZGY5ZTdmLWU5ZjYtNDBhZi1iNDM1LWFhYWFhYWFhYWFhYSIsImV4cCI6MTUwMDcyMDg3MSwibmJmIjoxNTAwNzIwMjcxfQ.RknlT5nD7XUzF6mQWfIHz5ob-FCNRCX1smO2_as0JJIrpiOASyPR-RNKeDF_ZDgesVTatyB8t8CQszqI3MpYwnA-wjS8-pSg74W7xFwaY76NOYlzuzLra03k5vgqQmCEm7Gj5WWFGFknMpOhxYuMeKlIh4TO-2rPkSOhWTQLbsehu5-vjnEY9F-Vh7EBlSU-6tJk6nYKUVfve3PM5uRdiaBPz6NC8Z3S34M-X_Lm9tQSVkh048GXAod-Dgz8-ib0r-DV3D7TQVWzmz0angGc94AvG2SE1E4Ge2eYgPOB24Zubi9WayrWMtVfU4pIvO-A0gOeBGl0s4PMcT4_ftPXxQ&owa=outlook.live.com&isc=1&isImagePreview=True" class = "logo">
          <%end%>
        </h3>



        </h3>
        <h3 class = " big_link border logo_color"><%=link_to "My Bets", matches_path%></h3>
        <h3 class = " big_link border logo_color"><%=link_to "Top Bets", matches_path%></h3>
          <div class = "sports">
          <li><div class = "s_sport" id = "soccer"> <img src="https://image.flaticon.com/icons/png/512/140/140389.png" width="20" height="20"> <%= "  "%><strong><%=@sports[0].name%> </strong> </div>  </li>
              <ul class = "initiallyHidden list-unstyled country"  id ="soccer_c">
                <%@country_soccer.each do |country|%>
                  <li>
                    <%=link_to country_games_path(country) do%>
                    <%=country.name%>
                    <%end%>
                  </li>
                <%end%>
              </ul>


          <li><div  class = "s_sport" id = "baseball"> <%= "  "%><img src="https://image.flaticon.com/icons/svg/140/140411.svg" width="20" height="20">  <strong><%=@sports[1].name%></strong>   </div></li>

              <ul class = "initiallyHidden list-unstyled country "  id ="baseball_c">
                <%@country_baseball.each do |country|%>
                  <li>
                    <%=country.name%>
                  </li>
                <%end%>
              </ul>

          <li><div class = "s_sport" id = "basketball"> <%= "  "%><img src="https://image.flaticon.com/icons/svg/140/140378.svg" width="20" height="20"> <strong><%=@sports[2].name%> </strong></div></li>

            <ul class = "initiallyHidden list-unstyled country"  id ="basketball_c">
                <%@country_basketball.each do |country|%>
                  <li>
                    <%=country.name%>
                  </li>
                <%end%>
              </ul>

          <li><div class = "s_sport" id = "football"> <%= "  "%><img src="https://image.flaticon.com/icons/svg/140/140333.svg" width="20" height="20" color = "white"> <strong><%=@sports[3].name%> </strong> </div></li>

              <ul class = "initiallyHidden list-unstyled country"  id ="football_c">
                <%@country_football.each do |country|%>
                <li>
                  <%=country.name%>
                </li>
                <%end%>
              </ul>

          <li><div class = "s_sport" id = "tennis">  <img src="https://image.flaticon.com/icons/svg/140/140400.svg" width= "20" height= "20"> <%= "  "%><strong><%=@sports[4].name%> </strong> </div></li>

              <ul class = "initiallyHidden list-unstyled country"  id ="tennis_c">
                <%@country_tennis.each do |country|%>
                <li>
                  <%=country.name%>
                </li>
                <%end%>
              </ul>

          <li><div class = "s_sport" id = "fight"> <img src="https://image.flaticon.com/icons/svg/140/140394.svg" width= "20" height="20"> <%= "  "%> <strong><%=@sports[5].name%> </strong></div></li>

               <ul class = "initiallyHidden list-unstyled country"  id ="fight_c">
                <%@country_fight.each do |country|%>
                <li>
                  <%=country.name%>
                </li>
                <%end%>
              </ul>
              </div>
      </ul>
      </div>
    </div>
  </div>
</div>