config/routes.rb
Rails.application.routes.draw do

  get 'pages_home'=> 'pages#home'
  get 'pages_landing'=> 'pages#landing'

   authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  root :to => "pages#landing"

resources :sports, only: :index

resources :countries, only: :index do
  resources :games, only: :index
end

# resources :users

resources :games, only: [:show, :top] do

  member do
    post :home
    post :away
  end

  resources :requests, only: [:index, :new, :create, :destroy]
end

  resources :requests, only: :index do

    member do
      post :display
    end

    resources :matches, only: [:new, :create]
  end

  resources :matches, only: [:index, :destroy]


  devise_for :users
  resources :users do
    resources :rbfriends, only: [:new, :destroy]
  end


  resources :rbfriends, only: :index do
    resources :betfriends, only: [:new, :destroy]
  end

  resources :betfriends, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


   # devise_for :users, controllers: {
   #      sessions: 'users/sessions'
   #    }

# devise_for :users,
#     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' },
#     path: "sessions"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/betfriend.rb
class Betfriend < ApplicationRecord
  belongs_to :rbfriend
  belongs_to :friend_a, class_name: 'User'
  belongs_to :friend_b, class_name: 'User'
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :sport
  has_many :games
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :request
end

app/models/rbfriend.rb
class Rbfriend < ApplicationRecord
  belongs_to :user
   belongs_to :send, class_name: 'User'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/requestf.rb
class Requestf < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController


  def index
    @game = Game.find(params[:game_id])
    @requests = Request.where(team_selected: @game.team_not_selected)
  end

  def new
    @game = Game.find(params[:game_id])
    @requests = Request.where(team_selected: @game.team_not_selected)
    @requests_true = @requests.where(display:true)
    @request_c = @requests.count
    @requests_true_c= @requests_true.count
    if @request_c != 0 && @requests_true_c > 0
      redirect_to game_requests_path
    else
      @game = Game.find(params[:game_id])
      @request = Request.new
    end
  end

  def create
    @request = Request.new(request_params)
    @game = Game.find(params[:game_id])
    @request.user = current_user
    @request.game = @game
    @request.team_selected = @game.team_selected
    @request.team_not_selected = @game.team_not_selected

    if @request.save
      flash[:notice] = "Your bet request has been sent, wait for a player to Match you!"
      redirect_to matches_path
    else
      render :new
    end

  end

  def destroy
  end


  def display
    @request = Request.find(params[:id])
    @request.display = false
    @request.save
    redirect_to new_request_match_path(@request)
  end

   private

  def request_params
    params.require(:request).permit(:amount, :user, :game)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/betfriends_helper.rb
module BetfriendsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rbfriends_helper.rb
module RbfriendsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/destroy.html.erb
<h1>Requests#destroy</h1>
<p>Find me in app/views/requests/destroy.html.erb</p>

app/views/requests/index.html.erb
<div class = "countainer ">
  <div class ="row">
    <div class = "col-xs-10 col-sm-offset-4 col-md-8 col-md-offset-3 text-center">
    <h4> Users who bet to <strong><%=@game.team_not_selected%></strong></h4>
      <p> Chose an opnent and match!</p>
      <div class = "index-request">
      <%@requests.each do |request|%>
      <%if request.display == true%>
        <ul  id= "request-card" class ="list-unstyled" >
        <div class ="user-card list-inline">
          <li id = "user"><%=request.user.email%></li>
          <il id ="amount"><%=request.amount%> <i class="fa fa-database" aria-hidden="true"></i></il>

           <%= simple_form_for request, url: display_request_path(request), method: :post do |f| %>
           <%= f.submit " Match this Bet", class: "btn-match" %>
            <% end %>
        </div>
        </ul>
        <%end%>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class = "container" id ="amount-modal">
  <div class = "row">
    <div class = "col-xs-10 col-sm-offset-4 col-md-8 col-md-offset-3">

      <%= simple_form_for [@game, @request] do |f| %>
        <% f.error_notification %>
        <%= f.input :amount %>
        <%= f.button :submit %>
      <%end%>