config/routes.rb
Rails.application.routes.draw do

  get 'pages_home'=> 'pages#home'
  get 'pages_landing'=> 'pages#landing'

   authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  root :to => "pages#landing"

resources :sports, only: :index

resources :countries, only: :index do
  resources :games, only: :index
end

# resources :users

resources :games, only: [:show, :top] do

  member do
    post :home
    post :away
  end

  resources :requests, only: [:index, :new, :create, :destroy]
end

  resources :requests, only: :index do

    member do
      post :display
    end

    resources :matches, only: [:new, :create]
  end

  resources :matches, only: [:index, :destroy]


  devise_for :users
  resources :users do
    resources :rbfriends, only: [:new, :destroy]
  end


  resources :rbfriends, only: :index do
    resources :betfriends, only: [:new, :destroy]
  end

  resources :betfriends, only: :index

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


   # devise_for :users, controllers: {
   #      sessions: 'users/sessions'
   #    }

# devise_for :users,
#     controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' },
#     path: "sessions"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/betfriend.rb
class Betfriend < ApplicationRecord
  belongs_to :rbfriend
  belongs_to :friend_a, class_name: 'User'
  belongs_to :friend_b, class_name: 'User'
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :sport
  has_many :games
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :country
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :request
end

app/models/rbfriend.rb
class Rbfriend < ApplicationRecord
  belongs_to :user
   belongs_to :send, class_name: 'User'
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/requestf.rb
class Requestf < ApplicationRecord
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @country = Country.find(params[:country_id])
    @sport = @country.sport
    @games = Game.where(country: @country.id)
  end

  def show
    @game = Game.find(params[:id])
  end


  def top
    @top_games = Game.where(top:true)
  end


  def home
    @game = Game.find(params[:id])
    @game.team_selected = @game.local
    @game.team_not_selected = @game.visit
    @game.save
    redirect_to new_game_request_path(@game)
  end

  def away
    @game = Game.find(params[:id])
    @game.team_selected = @game.visit
    @game.team_not_selected = @game.local
    @game.save
    redirect_to new_game_request_path(@game)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/betfriends_helper.rb
module BetfriendsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rbfriends_helper.rb
module RbfriendsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class ="container_games">
<div class = "countainer ">
  <div class ="row">
    <div class = "col-xs-10 col-sm-offset-4 col-md-8 col-md-offset-3">

  <%@games.each do |game|%>
    <ul class = "list-unstyled text-center">
    <div class = "game-card">
      <li class = "football"><img src="https://image.flaticon.com/icons/svg/140/140389.svg"></li>

      <small><li class ="date"><strong><%=game.date_show%></strong></li></small>
      <li class ="league"><strong><p><%=game.depor%><%=" "%><img src="https://image.flaticon.com/icons/svg/321/321260.svg" width="20" height="20"></p> </li></strong>
        <il class ="go"><%=link_to "PLAY!", game_path(game)%></il>
      <h3 class ="teams"><%=game.local%><%="  VS  "%> <%=game.visit%></h3>
    </div>
    </ul>
  <%end%>
 </div>
</div>
</div>
</div>

app/views/games/show.html.erb
<div class ="background_games">
<div class = "countainer">
  <div class ="row">
    <div class = "col-xs-10 col-sm-offset-4 col-md-8 col-md-offset-3">

    <div class = "show_games">
      <div>
        <p><%=@game.pct_team%></p>
        <%= simple_form_for @game, url: home_game_path(@game), method: :post do |f| %>
          <%= f.submit @game.local, class: "btn-request", data:{target: "#exampleModal", toggle: "modal"}%>
        <% end %>

      </div>

      <div>
        <h2><%=" VS "%></h2>
      </div>

      <div>
        <p> <%=@game.pct_tie%></p>
         <%= simple_form_for @game, url: away_game_path(@game), method: :post do |f| %>
          <%= f.submit @game.visit, class: "btn-request",  data:{target: "#myModal", toggle: "modal"}%>
          <% end %>

      </div>

        <div>
          <h3 class ="date_show"><%=@game.date_show%></h3>
        </div>
    </div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
    </div>
  </div>
</div>
    </div>